/** 
Author :     	Godwin Yusuf
Date: 	     	06:55 30/11/2023
Title: 	     	Resturant Sales Report
Tool: 	     	SQL on Github 
Project Source: https://www.kaggle.com/datasets/shariful07/student-mental-health
**/

RENAME TABLE  `week 40 - us christmas tree sales - 2010 to 2016`
TO ChristmasTree;


################################################################################

SELECT * FROM CHRISTMASTREE;


-- ANALYZE revenue over time
-- The Revenue generated by year.
####################################################################################

-- @Revenue
SELECT 
    YEAR,  SUM(SALES) AS `Revenue($)`
FROM
    CHRISTMASTREE
GROUP BY 1 
ORDER BY 2 DESC;

####################################################################################
-- @Revenue generated every year by type of tree @Real Tree
SELECT 
    YEAR, `Type of tree`, SUM(SALES) AS `Revenue($)`
FROM
    CHRISTMASTREE
    WHERE `type of tree` = "Real tree"
GROUP BY 1 
ORDER BY 2;

##################################################################################

-- @Revenue generated every year by type of tree @Fake Tree

SELECT 
    YEAR, `Type of tree`, SUM(SALES) AS `Revenue($)`
FROM
    CHRISTMASTREE
    WHERE `type of tree` = "fake tree"
GROUP BY 1 
ORDER BY 2;


###############################################################################
-- The number of trees sold each year
SELECT 
    YEAR,  SUM(`Number of trees sold`) AS TreeSale
FROM
    CHRISTMASTREE
GROUP BY 1 
ORDER BY 2;

###############################################################################
-- The number of trees sold each year @Tree type (Real Tree)
SELECT 
    YEAR,`Type of tree`, SUM(`Number of trees sold`) as TreeSale
FROM
    CHRISTMASTREE
    where `type of tree` = "Real tree"
GROUP BY 1 ,2
ORDER BY 1;

##################################################################################

-- The number of trees sold each year @Tree type (Real Tree)
SELECT 
    YEAR,`Type of tree`, SUM(`Number of trees sold`) AS TreeSale
FROM
    CHRISTMASTREE
    where `type of tree` = "fake tree"
GROUP BY 1 ,2
ORDER BY 1;

##################################################################################

-- Total Sale of Real Tree to fake tree.
SELECT `TYPE OF TREE`, SUM(SALES) AS TotalSale
FROM CHRISTMASTREE
GROUP BY 1;


#####################################################################################

-- total number of trees sold by year
SELECT 
    YEAR, SUM(`number of trees sold`) AS Y_SALE
FROM
    CHRISTMASTREE
GROUP BY 1
ORDER BY 2 DESC;




